package com.ruralhealth.gramasanjeevini

// This defines what a Medical Chain is. This MUST be here.
data class MedicalChain(
    val name: String,
    val description: String
)

object MedicalNetworkProvider {
    val fullChainList = listOf(
        MedicalChain("Jan Aushadhi Kendra", "13,000+ Govt Generic Medicine Stores"),
        MedicalChain("Apollo Pharmacy", "India's Largest Retail Network (5,500+ Stores)"),
        MedicalChain("MedPlus Pharmacy", "Second Largest Pharmacy Chain (4,200+ Stores)"),
        MedicalChain("Wellness Forever", "Top 24/7 Lifestyle & Pharmacy Network"),
        MedicalChain("Netmeds by Reliance", "Reliance Retail Digital Pharmacy Brand"),
        MedicalChain("Tata 1mg Store", "Premier Digital Health & Branded Meds"),
        MedicalChain("PharmEasy Store", "Major Online & Offline Medical Network"),
        MedicalChain("Zeno Health", "Leading Affordable Generic Medicine Chain"),
        MedicalChain("Generic Aadhaar", "Rapidly Growing Low-Cost Generic Network"),
        MedicalChain("Truemeds Pharmacy", "Generic Specialist & Delivery Network"),
        MedicalChain("Aster Pharmacy", "Integrated Hospital-Based Network"),
        MedicalChain("Manipal Pharmacy", "Premium Hospital-Linked Medical Store"),
        MedicalChain("Fortis Pharmacy", "Multi-Specialty Hospital Supply Chain"),
        MedicalChain("Max Healthcare Pharmacy", "Corporate Hospital Medicine Outlet"),
        MedicalChain("Narayana Health Pharmacy", "Affordable Multi-State Hospital Chain"),
        MedicalChain("Medanta Pharmacy", "Advanced Hospital Pharmaceutical Services"),
        MedicalChain("Kauvery Pharmacy", "Leading South India Hospital Network"),
        MedicalChain("Rainbow Pharmacy", "Pediatric & Family Care Specialist"),
        MedicalChain("AIIMS Pharmacy Outlet", "Govt Apex Hospital Medicine Supply"),
        MedicalChain("CMC Vellore Pharmacy", "Trusted Institutional Medical Supply"),
        MedicalChain("Patanjali Arogya Kendra", "Mass-Market Ayurvedic Medicine Hub"),
        MedicalChain("Himalaya Wellness Store", "Global Natural Healthcare Brand"),
        MedicalChain("Dabur Ayurvedic Pharmacy", "Trusted Herbal & Ayurvedic Solutions"),
        MedicalChain("Kottakkal Arya Vaidya Sala", "Traditional Authentic Ayurveda"),
        MedicalChain("Baidyanath Ayurved Bhawan", "Legendary Classical Formulations"),
        MedicalChain("Sri Sri Tattva Pharmacy", "Modern Holistic Ayurvedic Chain"),
        MedicalChain("Jiva Ayurveda Store", "Consultation & Ayurvedic Medicines"),
        MedicalChain("Organic India Store", "Natural Herbal Wellness Outlets"),
        MedicalChain("Oushadhi Pharmacy", "Govt Ayurvedic Medicine Manufacturing"),
        MedicalChain("Hamdard Wellness", "Unani & Herbal Health Provider"),
        MedicalChain("SehatSathi Pharmacy", "Bharat-Focused Health Companion Hub"),
        MedicalChain("RuralRx Pharmacy", "Simplified Medicine Access for Villages"),
        MedicalChain("GramAushadhi", "Village-Level Medicine Distribution"),
        MedicalChain("Swasth Bharat Pharmacy", "Healthy India Initiative Centers"),
        MedicalChain("Bharat MedCare", "Nationwide Rural Medicine Reach"),
        MedicalChain("Village MedStore", "Essential Local Community Hub"),
        MedicalChain("Seva Pharmacy", "Service-Oriented Village Medicine"),
        MedicalChain("Aastha Rural Health", "Trust-Based Local Pharmacy Network"),
        MedicalChain("GramSeva MedStore", "Dedicated Rural Citizen Support"),
        MedicalChain("JanHealth Kendra", "Affordable People-Centric Medicine"),
        MedicalChain("Frank Ross Pharmacy", "Historic East-India Medical Legacy"),
        MedicalChain("Guardian Pharmacy", "Trusted Neighborhood Chemist Chain"),
        MedicalChain("Noble Plus Pharmacy", "Premium Mumbai & Urban Retailer"),
        MedicalChain("Health & Glow", "Personal Care & Essential Meds"),
        MedicalChain("SastaSundar Health Mart", "Digital + Offline Budget Network"),
        MedicalChain("Blue Cross Medicals", "Popular Local Neighborhood Stores"),
        MedicalChain("LifeLine Medicals", "Emergency Medical Support Chain"),
        MedicalChain("Care Pharmacy Network", "Trusted Community Health Partner"),
        MedicalChain("Wellness Hub", "Daily Care and Family Medicine"),
        MedicalChain("MedKart Pharmacy", "Generic Medicine Specialist"),
        MedicalChain("HLL Lifecare Store", "Govt Affordable Life-Saving Drugs"),
        MedicalChain("Red Cross Medical Store", "Humanitarian Health Support"),
        MedicalChain("State Medical Corporation", "Govt Public Health Distribution"),
        MedicalChain("Life-Cell Support", "Critical & Stem Cell Care Network"),
        MedicalChain("RapidHeal Pharmacy", "Fast Recovery Medicine Chain"),
        MedicalChain("Suraksha Pharmacy", "Protective Healthcare Provider"),
        MedicalChain("JeevanRaksha Meds", "Life-Protection Medicine Network"),
        MedicalChain("FirstAid MedStore", "Immediate Crisis Care Pharmacy"),
        MedicalChain("VitalCare Hub", "Essential Medicine Distribution"),
        MedicalChain("PulseCare Medicals", "The Heart of Rural Healthcare"),
        MedicalChain("MedSaver Pharmacy", "Budget-Friendly Medicine Outlet"),
        MedicalChain("TrueCare Generic", "Honest & Reliable Generic Chain"),
        MedicalChain("PharmaDirect", "Direct-to-Citizen Medicine Supply"),
        MedicalChain("EasyCare Meds", "Simple Local Medicine Access"),
        MedicalChain("SwiftCare Pharmacy", "Rapid Local Supply Chain"),
        MedicalChain("DoorStep Meds", "Home Delivery Village Network"),
        MedicalChain("BudgetCare Hub", "Lowest Cost Village Medicine"),
        MedicalChain("Janata MedStore", "Peoples Choice for Medicines"),
        MedicalChain("EcoHealth Store", "Sustainable & Affordable Meds"),
        MedicalChain("SmartHealth Kendra", "Digital Ready Health Outlets"),
        MedicalChain("NovaHealth Pharmacy", "Next-Gen Medicine Access"),
        MedicalChain("AstraCare Meds", "Advanced Medical Supply Chain"),
        MedicalChain("Infinity Pharma", "Continuous Medicine Availability"),
        MedicalChain("PulseAxis Health", "Structured Healthcare Network"),
        MedicalChain("Zenith Pharmacy", "Top-Level Medical Service"),
        MedicalChain("EliteCare Meds", "Premium Village Health Support"),
        MedicalChain("Iconic Pharma", "Recognized Quality Medicine Brand"),
        MedicalChain("GlobalCare Network", "International Standard Local Stores"),
        MedicalChain("Alpha Meds", "Primary Health Connection Chain"),
        MedicalChain("Omega Pharmacy", "Complete Health Solutions Hub"),
        MedicalChain("Town Pharma", "Strong Local Village Connectivity"),
        MedicalChain("Bridge Meds", "Connecting Citizens to Healthcare"),
        MedicalChain("Core Health Store", "Fundamental Care for All Ages"),
        MedicalChain("Mega Meds", "Large Inventory Rural Stores"),
        MedicalChain("Shield Meds", "Safe & Protective Medicine Care"),
        MedicalChain("Pioneer Pharma", "First-in-Class Rural Pharmacy"),
        MedicalChain("Heritage Meds", "Traditional Values in Healthcare"),
        MedicalChain("Modern Pharma", "High-Tech Village Medicine Store"),
        MedicalChain("Summit Pharma", "Highest Quality Medical Standard"),
        MedicalChain("Horizon Meds", "The Future of Village Care"),
        MedicalChain("Unity Medicals", "United for Village Wellness"),
        MedicalChain("Sunrise Pharma", "Early Access Medical Support"),
        MedicalChain("Focus Meds", "Targeted Medicine Availability"),
        MedicalChain("Direct Pharmacy", "No Middleman Medicine Link"),
        MedicalChain("OpenCare Kendra", "Always Ready Health Services"),
        MedicalChain("Crossroads Meds", "Central Village Health Hub"),
        MedicalChain("Anchor Pharmacy", "Steady Support for Citizens"),
        MedicalChain("Compass Meds", "Guiding You to Better Health"),
        MedicalChain("Liberty Pharma", "Freedom to Choose Better Health"),
        MedicalChain("Classic Meds", "Old Trust in a Modern Platform"),
        MedicalChain("PureCare Meds", "No Compromise on Quality"),
        MedicalChain("SafeWay Pharma", "The Trusted Path to Recovery")
    )
}