package com.ruralhealth.gramasanjeevini

data class SymptomItem(
    val problem: String,
    val description: String,
    val relatedMeds: List<String>
)

object SymptomProvider {
    val commonSymptoms = listOf(
        SymptomItem("Acidity/Gas", "Stomach burning, chest burning", listOf("Digene", "Gelusil", "Pantoprazole (Pan 40)")),
        SymptomItem("Back Strain", "Pain from lifting heavy farm loads", listOf("Moov", "Volini Spray", "Hot Compress")),
        SymptomItem("Bad Breath", "Smelly mouth, gum bleeding", listOf("Listerine", "Gum Paint")),
        SymptomItem("Blocked Nose", "Difficulty breathing due to cold", listOf("Otrivin Nasal Drops", "Karvol Plus capsules")),
        SymptomItem("Body Pain", "Headache, backache, joint pain", listOf("Ibuprofen", "Diclofenac", "Zerodol")),
        SymptomItem("Boils (Phonsi)", "Painful pus-filled lump on skin", listOf("Magnesium Sulphate", "Mupirocin (Bactroban)")),
        SymptomItem("Child Fever", "Hot forehead in children", listOf("Crocin Kids", "P-120 Suspension")),
        SymptomItem("Choking", "Object stuck in throat, cannot breathe", listOf("Heimlich Maneuver", "Back Slaps")),
        SymptomItem("Colic (Baby Gas)", "Excessive crying, pulling legs to tummy", listOf("Colicaid Drops", "Woodward's Gripe Water")),
        SymptomItem("Common Cold", "Runny nose, sneezing, watery eyes", listOf("Cetirizine", "Okacet", "Solvin Cold")),
        SymptomItem("Constipation", "Hard stools, difficulty passing", listOf("Dulcolax", "Cremaffin", "Isabgol")),
        SymptomItem("Cracked Heels", "Painful cracks on feet from walking", listOf("Krack Cream", "Vaseline")),
        SymptomItem("Crop/Pollen Allergy", "Itching eyes/sneezing after harvesting", listOf("Allegra (Fexofenadine)", "Levocetirizine")),
        SymptomItem("Dandruff", "White flakes on scalp, itching", listOf("Ketoconazole (Nizoral)", "Selsun")),
        SymptomItem("Diabetes Check", "Excessive thirst, frequent urination", listOf("Metformin (Consult Dr)", "Sugar Test")),
        SymptomItem("Diaper Rash", "Redness in baby's diaper area", listOf("Zinc Oxide (Rashfree)", "Coconut Oil")),
        SymptomItem("Dog Bite", "EMERGENCY: Animal bite marks", listOf("Anti-Rabies (Hospital)", "Wash with Soap 15 mins")),
        SymptomItem("Dry Cough", "Itchy throat, no phlegm", listOf("Ascoril D", "Grilinctus", "Benadryl")),
        SymptomItem("Dry Mouth", "Thirst, sticky feeling in mouth", listOf("Drink Water", "Glycerin")),
        SymptomItem("Ear Pain", "Sharp pain or wax blockage", listOf("Otogesic Drops", "Waxolve")),
        SymptomItem("Electric Shock", "Numbness, burn marks from wires", listOf("Check Breathing", "Hospital Immediate")),
        SymptomItem("Eye Redness", "Dust allergy, burning sensation in eyes", listOf("Refresh Tears", "Moxifloxacin Drops")),
        SymptomItem("Fainting", "Sudden loss of consciousness", listOf("Raise Legs", "ORS after waking")),
        SymptomItem("Fever", "High body heat, chills, shivering", listOf("Paracetamol", "Dolo 650", "Calpol")),
        SymptomItem("Foot Rot", "Infection between toes in monsoon", listOf("Dusting Powder", "Keep Feet Dry")),
        SymptomItem("Fracture", "Bone deformity, unable to move limb", listOf("Splint/Support", "Painkiller (Hospital)")),
        SymptomItem("General Weakness", "Feeling tired, low energy", listOf("Multivitamin (Revital)", "Neurobion Forte")),
        SymptomItem("Head Lice", "Itching in hair, small eggs (nits)", listOf("Mediker Shampoo", "Permethrin Lotion")),
        SymptomItem("Heat Stroke", "Field work in sun: Dizziness, dry skin", listOf("ORS (Electral)", "Cool Water Sponging")),
        SymptomItem("Hiccups", "Continuous involuntary sound from throat", listOf("Hold Breath", "Drink Cold Water")),
        SymptomItem("High BP", "Dizziness, heavy head, blurring vision", listOf("Amlodipine (Consult Dr)", "Low Salt")),
        SymptomItem("Indigestion", "Heavy feeling after eating", listOf("Pudin Hara", "Enzoflam", "Zinetac")),
        SymptomItem("Iron Deficiency", "Paleness, getting tired very easily", listOf("Dexorange", "Orofer XT", "Autrin")),
        SymptomItem("Joint Stiffness", "Difficulty moving knees in morning", listOf("Glucosamine", "Rumalaya Gel")),
        SymptomItem("Loose Motion", "Watery stools, frequent visits", listOf("Loperamide", "Oflox-OZ", "ORS (Electral)")),
        SymptomItem("Migraine", "Severe one-sided headache, light sensitivity", listOf("Vasograin", "Naproxen")),
        SymptomItem("Minor Burns", "Heat/Fire burn from cooking or tools", listOf("Burnol (Silver Sulphadiazine)", "Coconut Oil")),
        SymptomItem("Minor Cuts", "Injury from farm tools/stones", listOf("Betadine (Povidone-Iodine)", "Clean with Soap")),
        SymptomItem("Morning Sickness", "Nausea/Vomiting during pregnancy", listOf("Doxylamine (Doxinate)", "Ginger Tea")),
        SymptomItem("Mouth Ulcers", "White sores in mouth, painful eating", listOf("Ora-fast Gel", "B-Complex (Becosules)")),
        SymptomItem("Mud Rash", "Fungal infection from wet fields/mud", listOf("Clotrimazole (Itch-Guard)", "Luliconazole")),
        SymptomItem("Muscle Cramps", "Pain in calf or legs after work", listOf("Magnesium", "ORSL Liquid")),
        SymptomItem("Nail Infection", "Swelling around fingernail or toenail", listOf("Candid Powder", "Betadine solution")),
        SymptomItem("Period Pain", "Menstrual cramps, lower back pain", listOf("Meftal Spas", "Cyclopam")),
        SymptomItem("Prickly Heat", "Small red bumps during summer (Ghamoria)", listOf("Dermicool Powder", "Nycil")),
        SymptomItem("Ringworm", "Circular red itchy patches on skin", listOf("Terbinafine (Tyza)", "Itch-Guard")),
        SymptomItem("Scabies", "Intense itching, small bumps", listOf("Permethrin Cream", "Benzyl Benzoate")),
        SymptomItem("Scorpion/Bee Sting", "Sharp stinging pain, local redness", listOf("Avil (Pheniramine)", "Calamine Lotion")),
        SymptomItem("Skin Itching", "Rashes, minor allergies, heat rash", listOf("Calamine", "Hydrocortisone", "Avil")),
        SymptomItem("Sleep Difficulty", "Unable to fall asleep", listOf("Melatonin", "Warm Milk")),
        SymptomItem("Snake Bite", "EMERGENCY: Fang marks, swelling, pain", listOf("ASV (Hospital Only)", "Keep Limb Still")),
        SymptomItem("Sore Throat", "Pain while swallowing, throat redness", listOf("Strepsils", "Kanthil", "Chlorhexidine Mouthwash")),
        SymptomItem("Stomach Pain", "Cramps, spasms in abdomen", listOf("Meftal Spas", "Cyclopam")),
        SymptomItem("Sunburn", "Red, painful skin after long sun exposure", listOf("Aloe Vera Gel", "Calamine")),
        SymptomItem("Teething Pain", "Baby crying, biting objects, drooling", listOf("Calcarea Phos", "Honey (Apply on gums)")),
        SymptomItem("Tonsillitis", "Swollen glands in throat, fever", listOf("Salt Water Gargle", "Amoxicillin (Dr)")),
        SymptomItem("Toothache", "Sharp pain in gums or teeth", listOf("Ketorolac (Keterol DT)", "Clove Oil")),
        SymptomItem("Travel Sickness", "Vomiting during bus/car ride", listOf("Avomine", "Domstal")),
        SymptomItem("Vomiting/Nausea", "Feeling like throwing up", listOf("Ondansetron (Ondem)", "Domperidone")),
        SymptomItem("Wet Cough", "Chest congestion, thick phlegm", listOf("Ambroxol", "Mucolite", "Terbutaline"))
    )
}